### PR TITLE
Fix dockerfile

### LINKED ISSUE #229: Update entrypoint in Dockerfile
As I figured out, adding the following line causes to compiling source files under `./dist/src/*` instead of `./dist/*`, that's why we need to update [entrypoint](https://github.com/api3dao/airseeker-v2/blob/aeea9d27eacdfe703d738efd194a1c8cb8daa94e/docker/Dockerfile#L26) of Dockerfile to be `/app/dist/src/index.js` 

https://github.com/api3dao/airseeker-v2/blob/2e8db23ab952e3cf21c19c307090c4ba529d00fe/tsconfig.json#L28

### PR DESCRIPTION
**Pull request by Siegrift**
Closes https://github.com/api3dao/airseeker-v2/issues/229

I tested this locally and it works. The change is similar to https://github.com/api3dao/signed-api/blob/7f30af2a5ada7abd7dc168da1032683b966410f8/packages/airnode-feed/src/validation/config.ts#L19

### CODE REVIEW

File: src/config/index.ts [hunk 1]
```diff
@@ -1,13 +1,18 @@
...
 import { goSync } from '@api3/promise-utils';
 import dotenv from 'dotenv';
 
 import { configSchema } from './schema';
 import { interpolateSecrets, parseSecrets } from './utils';
 
-export const getConfigPath = () => join(__dirname, '../../config');
+// When Airnode feed is built, the "/dist" file contains "src" folder and "package.json" and the config is expected to
+// be located next to the "/dist" folder. When run in development, the config is expected to be located next to the
+// "src" folder (one less import level). We resolve the config by CWD as a workaround. Since the Airnode feed is
```
Comment (bdrhn9) [inline src/config/index.ts]:
```suggestion
// "src" folder (one less import level). We resolve the config by CWD as a workaround. Since the Airseeker is
```

Nit: typo.

**Review by bdrhn9 — APPROVED** [review]
Tested locally, it works as expected.

File: src/config/index.ts (hunk 1 above)
Comment (Siegrift) [reply src/config/index.ts]: I certainly did not copy paste the function from anywhere 👀
