### PR TITLE
Fix gas fetching, improve tests

### LINKED ISSUE #218: Revisit how gas prices for sanitization are fetched
We currently fetch the gas price only when submitting update tx. This is quite rare and we end up with not having enough gas price data to sanitize gas prices.

See: https://api3workspace.slack.com/archives/C06R2JCFSS1/p1711559821427089?thread_ts=1711546852.953019&cid=C06R2JCFSS1

### PR DESCRIPTION
**Pull request by Siegrift**
Closes https://github.com/api3dao/airseeker-v2/issues/218

## Rationale

[Here](https://api3workspace.slack.com/archives/C05TQPT7PNJ/p1697793195536069) we've decided to make the gas fetching part of the "main" (update feeds) loop. The problem is that the gas was fetched from the RPC only before an update transaction was submitted.

Now it's fetched during the processing of each batch.

### CODE REVIEW

File: src/gas-price/gas-price.ts [hunk 1]
```diff
@@ -185,28 +193,23 @@ export const getRecommendedGasPrice = async (
   const percentileGasPrice = getPercentile(
     sanitizationPercentile,
     gasPrices.map((gasPrice) => gasPrice.price)
-  );
-  if (!percentileGasPrice) {
-    logger.warn('No historical gas prices to compute the percentile. Using the provider recommended gas price.');
-    return multiplyBigNumber(gasPrice, recommendedGasPriceMultiplier);
-  }
-
+  )!;
```
Comment (Siegrift) [inline src/gas-price/gas-price.ts:193]: Guaranteed to exist because the array is non-empty.

File: src/gas-price/gas-price.ts [hunk 2]
```diff
@@ -102,6 +102,38 @@ export const calculateScalingMultiplier = (
...
+    const feeData = await provider.getFeeData();
+    // We assume the legacy gas price will always exist. See:
+    // https://api3workspace.slack.com/archives/C05TQPT7PNJ/p1699098552350519
+    return feeData.gasPrice;
+  });
+  const gasPrice = goGasPrice.data;
+  if (!goGasPrice.success) {
+    if (!goGasPrice.success) logger.error('Failed to fetch gas price from RPC provider.', goGasPrice.error);
+    return null;
+  }
```
Comment (vponline) [inline src/gas-price/gas-price.ts]: This seems like a typo:
```suggestion
  if (!goGasPrice.success) {
    logger.error('Failed to fetch gas price from RPC provider.', goGasPrice.error);
    return null;
  }
```

**Review by vponline — APPROVED** [review]
LGTM, noticed one possible typo

File: src/gas-price/gas-price.ts [hunk 3]
```diff
@@ -126,40 +153,21 @@ export const getRecommendedGasPrice = async (
...
+  // Use the latest gas price that is stored in the state. We assume that the gas price is fetched frequently and has
+  // been fetched immediately before making this call. In case it fails, we fallback to the previously stored gas price.
+  if (gasPrices.length > 0) {
     const lastSavedTimestamp = Math.max(...gasPrices.map((gasPrice) => gasPrice.timestamp));
-    const lastSavedGasPrice = gasPrices.find((gasPrice) => gasPrice.timestamp === lastSavedTimestamp)!.price;
-
-    if (lastSavedTimestamp >= Math.floor(Date.now() / 1000) - 10 * dataFeedUpdateInterval) {
-      gasPrice = lastSavedGasPrice;
-    }
+    latestGasPrice = gasPrices.find((gasPrice) => gasPrice.timestamp === lastSavedTimestamp)!.price;
```
Comment (bdrhn9) [inline src/gas-price/gas-price.ts]: Nit: I'd rather to utilize lodash's `maxBy` function like:
```typescript
latestGasPrice = _.maxBy(gasPrices, 'timestamp').price
```

File: src/update-feeds-loops/update-feeds-loops.ts [hunk 4]
```diff
@@ -339,6 +339,10 @@ export const processBatch = async (
     }
   }
 
+  // Fetch the gas price regardless of whether there are any feeds to be updated or not in order for gas oracle to
+  // maintain historical gas prices.
+  await fetchAndStoreGasPrice(chainId, providerName, provider);
```
Comment (bdrhn9) [inline src/update-feeds-loops/update-feeds-loops.ts:344]: Instead of here, isn't it better to call this function on `runUpdateFeeds` function? Because there is no meaningful time between processBatch calls and it will cause redundant RPC calls. For example, if we have 200 feeds on a chain and batch size 10, we probably requests same gas price 20 times for each RPC provider.

**Review by bdrhn9 — APPROVED** [review]
I liked the optimizations :-) thanks for addressing them 🔥

File: src/update-feeds-loops/update-feeds-loops.ts (hunk 4 above)
Comment (Siegrift) [reply src/update-feeds-loops/update-feeds-loops.ts:344]: The [batches are staggered](https://github.com/api3dao/airseeker-v2/blob/22a1ddae6585c2c8eb79f4f08ff36899e2cd2bb8/src/update-feeds-loops/update-feeds-loops.ts#L201) so there is a time delay. If we only fetched in in `runUpdateFeeds` the last batch would use gas price old ~`dataFeedUpdateInterval`.

 I see the point with multiple RPC calls though, but I don't see a better place when to fetch this.

Comment (bdrhn9) [reply src/update-feeds-loops/update-feeds-loops.ts:344]: It makes sense. Your approach looks more proper 👍🏼

File: src/gas-price/gas-price.ts (hunk 2 above)
Comment (Siegrift) [reply src/gas-price/gas-price.ts]: Yeah, thanks.

File: src/gas-price/gas-price.ts (hunk 3 above)
Comment (Siegrift) [reply src/gas-price/gas-price.ts]: I dislike the shorthand property, because it has not a good TS support and can break when you rename the field. This is a bit more typesafe:
```
maxBy(gasPrices, (x) => x.timestamp)
```
