### PR TITLE
Fix gas price scaling

### LINKED ISSUE #223: Fix gas price scaling
[This check](https://github.com/api3dao/airseeker-v2/blob/e335a8579e851d5ea6db11d363eb329ac15ebc98/src/gas-price/gas-price.ts#L164) is wrong and prevents gas scaling.

Revisit the spec as well, because this is not as clear as it should. Also, the documentation for config fields provides very little detail.

### PR DESCRIPTION
**Pull request by Siegrift**
Closes https://github.com/api3dao/airseeker-v2/issues/223

## Rationale

There was a discrepancy in the implementation, originating from misalignment on how the gas oracle should be implemented.

### CODE REVIEW

File: src/gas-price/gas-price.ts [hunk 1]
```diff
@@ -161,15 +161,16 @@ export const getRecommendedGasPrice = async (
...
     const multiplier = calculateScalingMultiplier(
       recommendedGasPriceMultiplier,
       maxScalingMultiplier,
-      Math.floor(Date.now() / 1000) - lastUpdateTimestamp,
+      pendingPeriod,
       scalingWindow
     );
 
-    logger.warn('Scaling gas price.', { gasPrice: gasPrice.toString(), multiplier });
+    logger.warn('Scaling gas price.', { gasPrice: gasPrice.toString(), multiplier, pendingPeriod });
```
Comment (Siegrift) [inline src/gas-price/gas-price.ts:173]: I've added a `pendingPeriod` field, because it's quite important to know for how long the transaction is pending.

File: src/gas-price/gas-price.ts [hunk 2]
```diff
@@ -161,15 +161,16 @@ export const getRecommendedGasPrice = async (
   const lastUpdateTimestamp = sponsorLastUpdateTimestamp[sponsorWalletAddress];
 
   // Check if the next update is a retry of a pending transaction and if it has been pending longer than scalingWindow
```
Comment (vponline) [inline src/gas-price/gas-price.ts]:
```suggestion
  // Check if the next update is a retry of a pending transaction
```

**Review by vponline — APPROVED** [review]
LGTM, Thanks for fixing!

File: src/gas-price/gas-price.ts [hunk 3]
```diff
@@ -161,15 +161,16 @@ export const getRecommendedGasPrice = async (
...
-  if (lastUpdateTimestamp && lastUpdateTimestamp < Math.floor(Date.now() / 1000) - scalingWindow) {
+  if (lastUpdateTimestamp) {
+    const pendingPeriod = Math.floor(Date.now() / 1000) - lastUpdateTimestamp;
     const multiplier = calculateScalingMultiplier(
       recommendedGasPriceMultiplier,
       maxScalingMultiplier,
```
Comment (bdrhn9) [inline src/gas-price/gas-price.ts:168]: It's nit and not related to objective of this PR but I'd suggest renaming `maxScalingMultiplier` to `maxGasPriceMultiplier` or `maxRecommendedGasPriceMultiplier`. The current name, `maxScalingMultiplier`, doesn't convey the intended meaning effectively; it could be misinterpreted as a multiplier for `recommendedGasPriceMultiplier`.

**Review by bdrhn9 — APPROVED** [review]
It looks good to me 🔥

File: src/gas-price/gas-price.ts (hunk 3 above)
Comment (Siegrift) [reply src/gas-price/gas-price.ts:168]: Hehe, I actually was thinking similarly [here](https://github.com/api3dao/airseeker-v2/pull/224/commits/66cf9152da5989f87a86a1a3fa29e1bcf1f95d86#diff-a25ae601baae9bca444c00d66e4934596768a26eafd5208c8fa077dcf31b4ae9R40)
 but at the end didn't do it, because it would be a breaking change and I wasn't sure if I am not too subjective.
 
At the end I also accepted `maxScalingMultiplier` as a good name, because it's only applied during gas price scaling. I still think `baseGasPriceMultiplier` would be a better name compared to `recommendedGasPriceMultiplier`

Comment (Siegrift) [reply src/gas-price/gas-price.ts:168]: I feel like it's not worth doing (nor opening an issue for). If you feel otherwise, feel free to create the issue.

File: src/gas-price/gas-price.ts (hunk 2 above)
Comment (Siegrift) [reply src/gas-price/gas-price.ts]: Thanks.
