### PR TITLE
Fix ethers provider draining resources in case of failure

### LINKED ISSUE #210: Investigate faulty RPC crashing Airseeker
See: https://api3workspace.slack.com/archives/C05RMQJ3X2L/p1710849365824949?thread_ts=1710845451.000169&cid=C05RMQJ3X2L

There is some unhandled error caused by faulty RPC.

### PR DESCRIPTION
**Pull request by Siegrift**
Closes https://github.com/api3dao/airseeker-v2/issues/210

## Rationale

I made a function which creates the provider in safe way and tested it locally. I also [let ethers know of this incident](https://github.com/api3dao/airseeker-v2/issues/210#issuecomment-2009989322) as I think the implementation could change a little.

### CODE REVIEW

**Review by bdrhn9 — APPROVED** [review]
Thanks for addressing this issue, it looks good 🔥

File: src/update-feeds-loops/contracts.ts [hunk 1]
```diff
@@ -3,12 +3,36 @@ import {
...
   Api3ServerV1__factory as Api3ServerV1Factory,
 } from '@api3/contracts';
+import { go } from '@api3/promise-utils';
 import { ethers } from 'ethers';
 import { zip } from 'lodash';
 
 import type { AirnodeAddress, TemplateId } from '../types';
 import { decodeDapiName, deriveBeaconId } from '../utils';
 
+export const createProvider = async (url: string) => {
```
Comment (Siegrift) [inline src/update-feeds-loops/contracts.ts:13]: @aquarat provided a nicer alternative to this with the following gist:
```
const fetchClient = new FetchRequest(chain.rpcUrl);
  fetchClient.timeout = 10_000;

  const network = {
    name: chain.name,
    chainId: chain.chainId,
  };
  const providerPublic = new JsonRpcProvider(fetchClient, network, 
  {
    staticNetwork: Network.from(network.chainId), // or just network
  });
```

We know the chainID, but not the chain name. We could use `@api3/chains` for this, but I quite like that we "detect" the faulty providers this way, so I am keeping it this way. Shout if you have some strong preferences.
